# Generated by Django 5.1.3 on 2024-11-29 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('streetNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(max_length=20)),
                ('shipping_info_form', models.CharField(choices=[('SAME', 'Same'), ('DIFFERENT', 'Different')], max_length=10, null=True)),
                ('payment_method', models.CharField(choices=[('UPON_DELIVERY', 'Upon Delivery'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card'), ('PAYPAL', 'PayPal'), ('APPLE_PAY', 'Apple Pay')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DRAFT', 'Draft'), ('IN_PROGRESS', 'Any'), ('PAID_PAYPAL', 'Paid PP'), ('PAID', 'Paid'), ('SHIPPED', 'Shipped')], default=('PENDING', 'Pending'), max_length=50)),
                ('is_order_placed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_orders', to='elshop.contactdata')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_id', models.CharField(max_length=20)),
                ('item_name', models.CharField(max_length=100)),
                ('person_1', models.CharField(max_length=100)),
                ('person_2', models.CharField(max_length=100)),
                ('poster_layout', models.CharField(choices=[('1_1', '1'), ('1_2', '2'), ('2_2', '4'), ('2_3', '5'), ('3_3', '9'), ('3_4', '12')], max_length=10, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('poster_format', models.CharField(choices=[('Digital', 'digital'), ('A5', 'A5'), ('A4', 'A4'), ('A3', 'A3')], default='Digital', max_length=10)),
                ('poster_paper_type', models.CharField(choices=[('MATT', 'Matt'), ('GLOSSY', 'Glossy')], max_length=10, null=True)),
                ('poster_frame', models.CharField(choices=[('NO', 'No'), ('ANY', 'Any')], max_length=10)),
                ('results', models.JSONField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='elshop.order')),
            ],
        ),
        migrations.CreateModel(
            name='PosterItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('PL_1_DOUBLE_TEXT', 'PL_1_DOUBLE_TEXT'), ('PL_1_EMOJI', 'PL_1_EMOJI'), ('PL_2_FIRST_MESSAGE', 'PL_2_FIRST_MESSAGE'), ('PL_1_GM_TABLE', 'PL_1_GM_TABLE'), ('PL_1_GN_TABLE', 'PL_1_GN_TABLE'), ('PL_1_HOURS_CHART', 'PL_1_HOURS_CHART'), ('PL_2_ILY', 'PL_2_ILY'), ('PL_1_LONGEST_GHOST', 'PL_1_LONGEST_GHOST'), ('PL_1_RESPONSE_TIME', 'PL_1_RESPONSE_TIME'), ('PL_1_LAUGH', 'PL_1_LAUGH'), ('PL_1_SENT_IMAGE', 'PL_1_SENT_IMAGE'), ('PL_1_SENT_REELS', 'PL_1_SENT_REELS'), ('PL_1_SENT_VIDEO', 'PL_1_SENT_VIDEO'), ('PL_1_TIME_SPENT', 'PL_1_TIME_SPENT'), ('PL_2_TIMELINE', 'PL_2_TIMELINE'), ('PL_1_TOTAL_BAR', 'PL_1_TOTAL_BAR'), ('PL_1_TOTAL_HEART', 'PL_1_TOTAL_HEART'), ('PL_1_VOICE', 'PL_1_VOICE'), ('PL_2_WEEK_PIE', 'PL_2_WEEK_PIE'), ('PL_1_WORDS', 'PL_1_WORDS'), ('M_1_EMOJI', 'M_1_EMOJI'), ('M_1_FIRST_MESSAGE', 'M_1_FIRST_MESSAGE'), ('M_1_GM_TABLE', 'M_1_GM_TABLE'), ('M_1_GMGN_CHART', 'M_1_GMGN_CHART'), ('M_1_GN_TABLE', 'M_1_GN_TABLE'), ('M_2_HOURS_CHART', 'M_2_HOURS_CHART'), ('M_1_ILY', 'M_1_ILY'), ('M_1_LAUGH', 'M_1_LAUGH'), ('M_1_SENT_REELS', 'M_1_SENT_REELS'), ('M_1_SENT_TIKTOK', 'M_1_SENT_TIKTOK'), ('M_1_TIME_SPENT', 'M_1_TIME_SPENT'), ('M_2_TIMELINE', 'M_2_TIMELINE'), ('M_1_TOTAL_BAR', 'M_1_TOTAL_BAR'), ('M_1_TOTAL_HEART', 'M_1_TOTAL_HEART'), ('M_1_VOICE', 'M_1_VOICE'), ('M_2_WEEK_BAR', 'M_2_WEEK_BAR'), ('M_1_WORDS', 'M_1_WORDS'), ('C_1_DOUBLE_TEXT', 'C_1_DOUBLE_TEXT'), ('C_1_EMOJI', 'C_1_EMOJI'), ('C_1_FIRST_MESSAGE', 'C_1_FIRST_MESSAGE'), ('C_1_GMGN_CHART', 'C_1_GMGN_CHART'), ('C_1_GMGN_TABLE', 'C_1_GMGN_TABLE'), ('C_1_HOURS_CHART', 'C_1_HOURS_CHART'), ('C_1_ILY', 'C_1_ILY'), ('C_1_LAUGH', 'C_1_LAUGH'), ('C_1_LONGEST_GHOST', 'C_1_LONGEST_GHOST'), ('C_1_RESPONSE_TIME', 'C_1_RESPONSE_TIME'), ('C_1_SENT_MEDIA2', 'C_1_SENT_MEDIA2'), ('C_1_SENT_MEDIA', 'C_1_SENT_MEDIA'), ('C_1_SENT_REELS', 'C_1_SENT_REELS'), ('C_1_SENT_TIKTOK', 'C_1_SENT_TIKTOK'), ('C_1_TIME_SPENT', 'C_1_TIME_SPENT'), ('C_2_TIMELINE', 'C_2_TIMELINE'), ('C_1_TOTAL_PIE', 'C_1_TOTAL_PIE'), ('C_1_VOICE', 'C_1_VOICE'), ('C_1_WEEK_BAR', 'C_1_WEEK_BAR'), ('C_2_WEEK_PIE', 'C_2_WEEK_PIE')], max_length=25)),
                ('chart_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poster_items', to='elshop.cartitem')),
            ],
        ),
    ]
