# Generated by Django 5.1.3 on 2024-11-29 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteritem',
            name='chart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_items', to='elshop.cartitem'),
        ),
    ]
