# Generated by Django 5.1.3 on 2024-11-29 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elshop', '0002_alter_posteritem_chart_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posteritem',
            old_name='chart_item',
            new_name='cart_item',
        ),
    ]
