# Generated by Django 5.1.3 on 2024-11-30 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elshop', '0004_rename_item_type_posteritem_poster_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_orders', to='elshop.contactdata'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='person_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='person_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='poster_frame',
            field=models.CharField(choices=[('NO', 'No'), ('ANY', 'Any'), ('ANYA3', 'Any A3'), ('ANYA4', 'Any A4'), ('ANYA5', 'Any A5')], max_length=10),
        ),
    ]
