# Generated by Django 5.1.3 on 2024-11-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elshop', '0005_order_shipping_info_alter_cartitem_person_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='poster_format',
            field=models.CharField(choices=[('DIGITAL', 'digital'), ('A5', 'A5'), ('A4', 'A4'), ('A3', 'A3')], default='DIGITAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='poster_frame',
            field=models.CharField(blank=True, choices=[('NO', 'No'), ('ANY', 'Any'), ('ANYA3', 'Any A3'), ('ANYA4', 'Any A4'), ('ANYA5', 'Any A5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='poster_paper_type',
            field=models.CharField(blank=True, choices=[('MATT', 'Matt'), ('GLOSSY', 'Glossy')], max_length=10, null=True),
        ),
    ]
